linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - goimports
    - misspell
    - revive

issues:
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - errcheck
