name: Test

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Install just
      uses: extractions/setup-just@v2

    - name: run tests
      run: just test-coverage

    - name: upload coverage reselt to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        flags: unit

    services:
      httpbin:
        image: kennethreitz/httpbin
        ports:
          - 9999:80


